--Workbook
--BASIC SELECT --
--Q1
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열 FROM TB_DEPARTMENT;
--Q2
SET SERVEROUTPUT ON; 
--Q9
select distinct category from tb_department;
DECLARE
V_DEP TB_DEPARTMENT.DEPARTMENT_NAME%TYPE;
V_CAP TB_DEPARTMENT.CAPACITY%TYPE;
V_NO TB_DEPARTMENT.DEPARTMENT_NO%TYPE;
BEGIN

SELECT DEPARTMENT_NAME , CAPACITY, DEPARTMENT_NO INTO V_DEP , V_CAP, V_NO 
FROM TB_DEPARTMENT WHERE DEPARTMENT_NO = '&DEPARTMENT_NO';
    
    DBMS_OUTPUT.PUT_LINE(V_DEP|| '의 정원은 ' || V_CAP ||'명 입니다.');
END;
/

-----------------------------------------------------------------------------
--ADDITIONAL SELECT - 함수 ----
--Q1
SELECT DEPARTMENT_NO , STUDENT_NAME , ENTRANCE_DATE FROM TB_STUDENT ORDER BY ENTRANCE_DATE ASC;
--Q2
SELECT PROFESSOR_NAME , PROFESSOR_SSN FROM TB_PROFESSOR WHERE PROFESSOR_NAME NOT LIKE '___' ;
----------------------------------------------------------------------------------
--ADDITIONAL SELECT - OPTION ----
--Q1
SELECT STUDENT_NAME , STUDENT_ADDRESS FROM TB_STUDENT ORDER BY STUDENT_NAME ASC;

--Q2
SELECT STUDENT_NAME , STUDENT_SSN FROM TB_STUDENT WHERE ABSENCE_YN = 'Y' ;
--Q9
select * from tb_class;
select * from tb_professor;
select class_name , professor_name from tb_class join tb_professor using (department_no) where professor_name in ('김선정','강혁'); 
--Q10
select * from tb_grade;
select * from tb_student;
select * from tb_DEPARTMENT;
SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME ='음악학과';
select STUDENT_NO , point , STUDENT_NAME from TB_STUDENT  join TB_GRADE using (STUDENT_NO) join TB_DEPARTMENT USING(DEPARTMENT_NO) where DEPARTMENT_NAME = '음악학과';
--Q17
select * from tb_student;
select * from tb_class;
SELECT  CLASS_NAME FROM TB_CLASS JOIN TB_STUDENT USING (DEPARTMENT_NO) WHERE STUDENT_NAME = '최경희';
SELECT DISTINCT STUDENT_NAME , STUDENT_ADDRESS FROM TB_STUDENT  JOIN TB_CLASS  USING (DEPARTMENT_NO) WHERE CLASS_NAME IN (SELECT  CLASS_NAME FROM TB_CLASS JOIN TB_STUDENT USING (DEPARTMENT_NO) WHERE STUDENT_NAME = '최경희');
--DDL --------------------------------------------------------
--Q1
CREATE TABLE TB_CATEGORY(
NAME VARCHAR2(40) PRIMARY KEY,
USE_YN CHAR(1) DEFAULT 'Y'
);
DROP TABLE TB_CATEGORY;
--Q2
CREATE TABLE TB_CLASS_TYPE(
NO VARCHAR2(5) PRIMARY KEY,
NAME VARCHAR2(20)
);
--Q9 *** 해결 못한 문제 ***

DESC TB_DEPARTMENT;

ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(NAME);
--Q10
GRANT CREATE VIEW TO KH;
SELECT * FROM TB_STUDENT;
CREATE VIEW VW_학생일반정보(학번,학생이름,주소) AS
SELECT STUDENT_NO , STUDENT_NAME , STUDENT_ADDRESS FROM TB_STUDENT;
--DML

--Q1
DROP TABLE TB_CLASS_TYPE;
SELECT * FROM TB_CLASS_TYPE;
INSERT INTO TB_CLASS_TYPE VALUES(01,'전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02,'전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03,'교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04,'교양선택');
INSERT INTO TB_CLASS_TYPE VALUES(05,'논문지도');



SELECT * FROM TB_CLASS_TYPE;

--Q2
CREATE TABLE TB_학생일반정보(
STUDENT_NO NUMBER,
STUDENT_NAME VARCHAR2(20),
ADDRESS VARCHAR2(40)
);
COMMENT ON COLUMN  TB_학생일반정보.STUDENT_NO IS '학번';
COMMENT ON COLUMN  TB_학생일반정보.STUDENT_NAME IS '학생이름';
COMMENT ON COLUMN  TB_학생일반정보.ADDRESS IS '주소';