--Workbook
--BASIC SELECT --
--Q1
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열 FROM TB_DEPARTMENT;
--Q2
SET SERVEROUTPUT ON; 

DECLARE
V_DEP TB_DEPARTMENT.DEPARTMENT_NAME%TYPE;
V_CAP TB_DEPARTMENT.CAPACITY%TYPE;
V_NO TB_DEPARTMENT.DEPARTMENT_NO%TYPE;
BEGIN

SELECT DEPARTMENT_NAME , CAPACITY, DEPARTMENT_NO INTO V_DEP , V_CAP, V_NO 
FROM TB_DEPARTMENT WHERE DEPARTMENT_NO = '&DEPARTMENT_NO';
    
    DBMS_OUTPUT.PUT_LINE(V_DEP|| '의 정원은 ' || V_CAP ||'명 입니다.');
END;
/
-----------------------------------------------------------------------------
--ADDITIONAL SELECT - 함수 ----
--Q1
SELECT DEPARTMENT_NO , STUDENT_NAME , ENTRANCE_DATE FROM TB_STUDENT ORDER BY ENTRANCE_DATE ASC;
--Q2
SELECT PROFESSOR_NAME , PROFESSOR_SSN FROM TB_PROFESSOR WHERE PROFESSOR_NAME NOT LIKE '___' ;
----------------------------------------------------------------------------------
--ADDITIONAL SELECT - OPTION ----
--Q1
SELECT STUDENT_NAME , STUDENT_ADDRESS FROM TB_STUDENT ORDER BY STUDENT_NAME ASC;

--Q2
SELECT STUDENT_NAME , STUDENT_SSN FROM TB_STUDENT WHERE ABSENCE_YN = 'Y' ;